site_name: ""
# site_url: https://gowt.dev
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: black
    - scheme: slate
      primary: deep orange
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top 
    - content.code.copy
    - search.suggest
    - search.highlight
  logo: null
  hide:
    - title
  include_search_page: false
  include_nav_footer: false
  custom_dir: overrides

extra_css:
- css/custom.css

plugins: []

docs_dir: source
site_dir: docs 

nav:
  - Home: index.md
  - Linux: 
    - Overview: Linux/index.md
    - Getting Started:
      - pre-work: Linux/Home.md
      - First Things First: Linux/First-things-First.md
    - System Setup:
      - Customization: Linux/Customization.md
      - Network Drives: Linux/Network-drives.md
      - Tweaks: Linux/Tweaks.md
    - Software:
      - Common: Linux/Common-Softwares.md
      - User Specific: Linux/User-specific-softwares.md
    - Development:
      - Git: Linux/Git.md
      - Coding: Linux/Coding.md
    - Debian 13 (Trixie): Linux/Trixie.md

  - Power system:
    - Overview: Power_systems/index.md

