site_name: "gowt.dev"
# site_url: https://gowt.dev
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.top 
    # - navigation.tabs.sticky
    - content.code.copy
    - search.suggest
    - toc.integrate

  logo: null
  hide:
    - title
  include_search_page: false
  custom_dir: overrides
  

extra:
  generator: false

extra_css:
- css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

docs_dir: source
site_dir: docs 

nav:
  - Home: index.md
  - Linux: 
    - Overview: Linux/index.md
    - Getting Started:
      - Debian-setup: Linux/Setup/Debian-setup.md
      - First Things First: Linux/Setup/First-things-First.md
      - Common Problems: Linux/Setup/Common-problems.md
    - System Setup:
      - Customization: Linux/Customization/Customization.md
      - Tweaks: Linux/Customization/Tweaks.md
    - Software:
      - Docker: Linux/Software/Docker.md
      - Mini-forge: Linux/Software/Mini-forge.md
      - Matlab: Linux/Software/Matlab.md
      - Codium: Linux/Software/Codium.md
      - Zotero: Linux/Software/Zotero.md
      - Kicad: Linux/Software/kicad.md
    - Development:
      - Git: Linux/Development/Git.md

  - Power system:
    - Overview: Power_systems/index.md

