site_name: ""
# site_url: https://gowt.dev
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: black
    - scheme: slate
      primary: deep orange
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top 
    - content.code.copy
    - search.suggest
    - search.highlight
  logo: null
  hide:
    - title
  include_search_page: false
  include_nav_footer: false
  custom_dir: overrides

extra_css:
- css/custom.css

markdown_extensions:
  - admonition

plugins:
  - search
  - mermaid2

docs_dir: source
site_dir: docs 

nav:
  - Home: index.md
  - Linux: 
    - Overview: Linux/index.md
    - Getting Started:
      - Debian-setup: Linux/Setup/Debian-setup.md
      - First Things First: Linux/Setup/First-things-First.md
      - Network Drives: Linux/Setup/Network-drives.md
    - System Setup:
      - Customization: Linux/Customization/Customization.md
      - Tweaks: Linux/Customization/Tweaks.md
    - Software:
      - Common: Linux/Software/Common-Softwares.md
      - User Specific: Linux/Software/User-specific-softwares.md
      - Coding: Linux/Software/Coding.md
    - Development:
      - Git: Linux/Development/Git.md

  - Power system:
    - Overview: Power_systems/index.md

