[project]
name = "knowledge-hub"
version = "0.1.0"
description = "documentation"
authors = [{ name = "Gowtham Mahendran" }]
requires-python = ">=3.10"

dependencies = [
  "mkdocs",
  "mkdocs-material",
  "mkdocs-mermaid2-plugin"
]